# Generated by Django 2.0.5 on 2018-05-04 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('is_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='first_exam',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='second_exam',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='third_exam',
        ),
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='example',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Quiz'),
        ),
    ]
