# Generated by Django 2.0.5 on 2018-05-04 09:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180504_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='quiz',
            name='first_exam',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='second_exam',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='third_exam',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
