# Generated by Django 2.0.5 on 2018-05-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180504_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
