# Generated by Django 2.0.5 on 2018-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quiz_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='id',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
